# Generated by Django 6.0.6 on 2026-07-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Waste_Request',
            fields=[
                ('custom_waste_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('total_amount', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HKS',
            fields=[
                ('hks_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('custom', 'Custom'), ('delivery', 'Delivery')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Notification',
            fields=[
                ('it_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Master',
            fields=[
                ('om_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='products/')),
                ('stock', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Public_Waste',
            fields=[
                ('public_waste_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='public_waste/')),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cust_Payment',
            fields=[
                ('cust_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('custom_waste_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.custom_waste_request')),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Waste_Status',
            fields=[
                ('custom_waste_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('plastic_quantity', models.CharField(max_length=255)),
                ('plastic_amount', models.CharField(max_length=255)),
                ('bio_quantity', models.CharField(max_length=255)),
                ('bio_amount', models.CharField(max_length=255)),
                ('custom_waste_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.custom_waste_request')),
            ],
        ),
        migrations.CreateModel(
            name='HKS_Notification',
            fields=[
                ('hks_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('hks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.hks')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Officer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='hks',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.login'),
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaints_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('date', models.CharField(max_length=255)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_complaints', to='hksapp.login')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaints', to='hksapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='OD_Payment',
            fields=[
                ('od_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('om_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.order_master')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Child',
            fields=[
                ('oc_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('om_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.order_master')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('rewards_id', models.AutoField(primary_key=True, serialize=False)),
                ('rewards', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('public_waste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.public_waste')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_owner_name', models.CharField(max_length=255)),
                ('building_number', models.CharField(max_length=255)),
                ('housename', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.login')),
                ('ward_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hksapp.ward')),
            ],
        ),
        migrations.AddField(
            model_name='public_waste',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.user'),
        ),
        migrations.AddField(
            model_name='order_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.user'),
        ),
        migrations.CreateModel(
            name='My_Waste',
            fields=[
                ('my_waste_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='custom_waste_request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.user'),
        ),
        migrations.CreateModel(
            name='Assign_Ward',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('hks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.hks')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hksapp.ward')),
            ],
        ),
    ]
