# Generated by Django 6.0.6 on 2026-07-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hksapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_waste',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='public_waste',
            name='longitude',
        ),
    ]
